import { useEffect, useState, type RefObject } from "react";
import type { EditorRef } from "@/components/editor/core/Editor";
import { renderMermaidSvgForExport } from "@/lib/imageExport/mermaid";
import { ArtifactActions } from "./ArtifactActions";
import { createMermaidArtifactBlocks, insertArtifactBlocks } from "./insertArtifact";
import { useSettings } from "@/stores/useSettings";
import { useResolvedTheme } from "@/hooks/useResolvedTheme";

interface DiagramCardProps {
  title?: string;
  source: string;
  editorRef?: RefObject<EditorRef | null>;
}

export function DiagramCard({ title, source, editorRef }: DiagramCardProps) {
  const theme = useSettings((state) => state.theme);
  const resolvedTheme = useResolvedTheme(theme);
  const [svg, setSvg] = useState("");
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let active = true;

    const render = async () => {
      setFailed(false);
      try {
        const nextSvg = await renderMermaidSvgForExport(source, resolvedTheme);
        if (active) setSvg(nextSvg);
      } catch {
        if (active) {
          setSvg("");
          setFailed(true);
        }
      }
    };

    if (source.trim()) void render();
    return () => {
      active = false;
    };
  }, [resolvedTheme, source]);

  return (
    <div className="group relative my-2 overflow-hidden rounded-[8px] border border-border bg-background">
      <ArtifactActions
        copySource={source}
        downloadSource={svg}
        filename="diagram.svg"
        mimeType="image/svg+xml;charset=utf-8"
        onInsert={() => insertArtifactBlocks(
          editorRef,
          createMermaidArtifactBlocks(title, source),
        )}
      />
      {title ? (
        <div className="border-b border-border/70 px-3 py-2 text-xs font-medium text-foreground">
          {title}
        </div>
      ) : null}
      <div className="min-h-[180px] overflow-x-auto px-3 py-4">
        {svg ? (
          <div
            aria-hidden="true"
            className="notebook-ai-artifact-svg mx-auto flex min-w-full w-max justify-center"
            // Mermaid output is generated by the local renderer, not raw model HTML.
            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{ __html: svg }}
          />
        ) : failed ? (
          <div className="flex min-h-[160px] items-center justify-center text-xs text-muted-foreground">
            图形生成失败
          </div>
        ) : (
          <div className="flex min-h-[160px] items-center justify-center text-xs text-muted-foreground">
            正在生成图形
          </div>
        )}
      </div>
    </div>
  );
}
