import { useEffect, useState } from "react";
import { importMarkdownFragment } from "@/lib/export";
import { renderMermaidSvgForExport } from "@/lib/imageExport/mermaid";
import { usePages } from "@/stores/usePages";
import { ArtifactActions } from "./ArtifactActions";

interface DiagramCardProps {
  title?: string;
  source: string;
}

function isDark() {
  const root = document.documentElement;
  return root.classList.contains("dark") || root.dataset.theme === "dark";
}

async function appendMermaidToCurrentPage(title: string | undefined, source: string) {
  const pageId = usePages.getState().activePageId;
  if (!pageId) return false;

  const markdown = `${title ? `### ${title}\n\n` : ""}\`\`\`mermaid\n${source.trim()}\n\`\`\``;
  const blocks = importMarkdownFragment(markdown);
  if (!blocks) return false;
  return usePages.getState().appendPageContent(pageId, blocks);
}

export function DiagramCard({ title, source }: DiagramCardProps) {
  const [svg, setSvg] = useState("");
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let active = true;

    const render = async () => {
      setFailed(false);
      try {
        const nextSvg = await renderMermaidSvgForExport(source, isDark() ? "dark" : "light");
        if (active) setSvg(nextSvg);
      } catch {
        if (active) {
          setSvg("");
          setFailed(true);
        }
      }
    };

    if (source.trim()) void render();
    return () => {
      active = false;
    };
  }, [source]);

  return (
    <div className="group relative my-2 overflow-hidden rounded-[8px] border border-border bg-background">
      <ArtifactActions
        copySource={source}
        downloadSource={svg}
        filename="diagram.svg"
        mimeType="image/svg+xml;charset=utf-8"
        onInsert={() => appendMermaidToCurrentPage(title, source)}
      />
      {title ? (
        <div className="border-b border-border/70 px-3 py-2 text-xs font-medium text-foreground">
          {title}
        </div>
      ) : null}
      <div className="min-h-[180px] overflow-x-auto px-3 py-4">
        {svg ? (
          <div
            aria-hidden="true"
            className="mx-auto flex min-w-max justify-center [&>svg]:max-h-[420px]"
            // Mermaid output is generated by the local renderer, not raw model HTML.
            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{ __html: svg }}
          />
        ) : failed ? (
          <div className="flex min-h-[160px] items-center justify-center text-xs text-muted-foreground">
            图形生成失败
          </div>
        ) : (
          <div className="flex min-h-[160px] items-center justify-center text-xs text-muted-foreground">
            正在生成图形
          </div>
        )}
      </div>
    </div>
  );
}
