import type { CardTheme } from "../types";

export const ARTISTIC_THEMES: CardTheme[] = [
  // ── 3. Medium ────────────────────────────────────────────────
  {
    id: "medium",
    name: "Medium 杂志",
    nameEn: "Medium",
    description: "衬线大标题，阅读感",
    tags: ["杂志", "阅读"],
    mode: "light",
    titleFont: "'Noto Serif SC', 'Georgia', 'Times New Roman', serif",
    bodyFont: "'Noto Serif SC', 'Georgia', 'Times New Roman', serif",
    codeFont: "'JetBrains Mono', 'SF Mono', monospace",
    titleFontSize: 34,
    titleFontWeight: 400,
    titleLineHeight: 1.2,
    titleLetterSpacing: "-0.01em",
    titleAlign: "center",
    bodyFontSize: 16,
    bodyLineHeight: 1.9,
    bodyLetterSpacing: "0.01em",
    background: "#faf9f6",
    cardBg: "#ffffff",
    textColor: "#292929",
    secondaryText: "#757575",
    accent: "#1a8917",
    codeBg: "#f7f7f7",
    quoteBorder: "#e5e5e5",
    calloutBg: "#f9f9f9",
    tableBorder: "#e5e5e5",
    divider: "#e5e5e5",
    watermark: "#d4d4d4",
    containerPaddingX: 64,
    containerPaddingY: 64,
    cardPaddingX: 48,
    cardPaddingY: 48,
    cardRadius: 4,
    cardBorder: "none",
    cardShadow: "0 2px 8px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.06)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 4. Kenya Hara ────────────────────────────────────────────
  {
    id: "kenya-hara",
    name: "原研哉·白",
    nameEn: "Kenya Hara",
    description: "极致留白，东方禅意",
    tags: ["极简", "设计"],
    mode: "light",
    titleFont: "'Noto Sans SC', 'Helvetica Neue', sans-serif",
    bodyFont: "'Noto Sans SC', 'Helvetica Neue', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 20,
    titleFontWeight: 300,
    titleLineHeight: 1.6,
    titleLetterSpacing: "0.15em",
    titleAlign: "left",
    bodyFontSize: 14,
    bodyLineHeight: 2.2,
    bodyLetterSpacing: "0.05em",
    background: "#fefefe",
    cardBg: "transparent",
    textColor: "#333333",
    secondaryText: "#999999",
    accent: "#888888",
    codeBg: "#f8f8f8",
    quoteBorder: "#dddddd",
    calloutBg: "#fafafa",
    tableBorder: "#eeeeee",
    divider: "#eeeeee",
    watermark: "#cccccc",
    containerPaddingX: 80,
    containerPaddingY: 80,
    cardPaddingX: 0,
    cardPaddingY: 0,
    cardRadius: 0,
    cardBorder: "none",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: false,
  },

  // ── 5. Typewriter ────────────────────────────────────────────
  {
    id: "typewriter",
    name: "复古打字机",
    nameEn: "Typewriter",
    description: "米黄纸张，文学气息",
    tags: ["复古", "文学"],
    mode: "light",
    titleFont: "'Courier Prime', 'Noto Serif SC', 'Songti SC', serif",
    bodyFont: "'Courier Prime', 'Noto Serif SC', 'Songti SC', serif",
    codeFont: "'Courier Prime', monospace",
    titleFontSize: 24,
    titleFontWeight: 700,
    titleLineHeight: 1.4,
    titleLetterSpacing: "0.02em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.85,
    bodyLetterSpacing: "0.01em",
    background: "#f5f0e6",
    cardBg: "#faf6ed",
    textColor: "#3d3225",
    secondaryText: "#8a7e6b",
    accent: "#8b4513",
    codeBg: "#f0ebe0",
    quoteBorder: "#d4c9b8",
    calloutBg: "#f5f0e4",
    tableBorder: "#d4c9b8",
    divider: "#d4c9b8",
    watermark: "#d8cfc4",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 40,
    cardRadius: 2,
    cardBorder: "1px solid #e8e0d0",
    cardShadow: "0 1px 4px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.04), inset 0 0 60px rgba(139,69,19,0.02)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 7. Academic ──────────────────────────────────────────────
  {
    id: "academic",
    name: "学术 LaTeX",
    nameEn: "Academic",
    description: "严谨排版，论文感",
    tags: ["学术", "严肃"],
    mode: "light",
    titleFont: "'Noto Serif SC', 'Times New Roman', 'Georgia', serif",
    bodyFont: "'Noto Serif SC', 'Times New Roman', 'Georgia', serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 22,
    titleFontWeight: 700,
    titleLineHeight: 1.4,
    titleLetterSpacing: "0",
    titleAlign: "center",
    bodyFontSize: 15,
    bodyLineHeight: 1.75,
    bodyLetterSpacing: "0",
    background: "#ffffff",
    cardBg: "#ffffff",
    textColor: "#000000",
    secondaryText: "#555555",
    accent: "#0066cc",
    codeBg: "#f8f8f8",
    quoteBorder: "#cccccc",
    calloutBg: "#fafafa",
    tableBorder: "#cccccc",
    divider: "#cccccc",
    watermark: "#bbbbbb",
    containerPaddingX: 64,
    containerPaddingY: 64,
    cardPaddingX: 48,
    cardPaddingY: 40,
    cardRadius: 0,
    cardBorder: "1px solid #e0e0e0",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 8. Stationery ────────────────────────────────────────────
  {
    id: "stationery",
    name: "手账便签",
    nameEn: "Stationery",
    description: "温暖手写，生活气息",
    tags: ["手写", "温馨"],
    mode: "light",
    titleFont: "'ZCOOL XiaoWei', 'Ma Shan Zheng', 'Noto Sans SC', cursive",
    bodyFont: "'ZCOOL XiaoWei', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 26,
    titleFontWeight: 400,
    titleLineHeight: 1.4,
    titleLetterSpacing: "0.04em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.85,
    bodyLetterSpacing: "0.02em",
    background: "#fef9e7",
    cardBg: "#fffef5",
    textColor: "#4a4035",
    secondaryText: "#9a8e7e",
    accent: "#d97706",
    codeBg: "#faf5e6",
    quoteBorder: "#e8dcc8",
    calloutBg: "#fdf8ed",
    tableBorder: "#e8dcc8",
    divider: "#e8dcc8",
    watermark: "#ddd5c8",
    containerPaddingX: 52,
    containerPaddingY: 52,
    cardPaddingX: 36,
    cardPaddingY: 36,
    cardRadius: 12,
    cardBorder: "1px solid #f0e8d0",
    cardShadow: "0 2px 8px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.03), inset 0 1px 0 rgba(255,255,255,0.8)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 17. Mocha Mousse (Pantone-inspired) ──────────────────────
  {
    id: "mocha-mousse",
    name: "摩卡慕斯",
    nameEn: "Mocha Mousse",
    description: "暖棕大地色，2025 年度风",
    tags: ["浅色", "温暖"],
    mode: "light",
    titleFont: "'Fraunces', 'Noto Serif SC', Georgia, serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 30,
    titleFontWeight: 500,
    titleLineHeight: 1.25,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0.005em",
    background: "#f5ede0",
    cardBg: "#fdf8ee",
    textColor: "#3d2f24",
    secondaryText: "#8a7560",
    accent: "#a47864",
    codeBg: "#ede3d3",
    quoteBorder: "#c9b8a3",
    calloutBg: "#f5ede0",
    tableBorder: "#d8c8b3",
    divider: "#e5d8c4",
    watermark: "#b8a690",
    containerPaddingX: 60,
    containerPaddingY: 60,
    cardPaddingX: 44,
    cardPaddingY: 42,
    cardRadius: 18,
    cardBorder: "none",
    cardShadow: "0 4px 24px rgba(164,120,100,0.1), 0 1px 2px rgba(164,120,100,0.06)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 19. Brutalist ────────────────────────────────────────────
  {
    id: "brutalist",
    name: "野性印刷",
    nameEn: "Brutalist",
    description: "硬边大字 + 实心投影，叛逆派",
    tags: ["浅色", "特立独行"],
    mode: "light",
    titleFont: "'Space Grotesk', 'Inter', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 42,
    titleFontWeight: 700,
    titleLineHeight: 1.02,
    titleLetterSpacing: "-0.04em",
    titleAlign: "left",
    bodyFontSize: 16,
    bodyLineHeight: 1.6,
    bodyLetterSpacing: "0",
    background: "#f5f5f5",
    cardBg: "#ffffff",
    textColor: "#0a0a0a",
    secondaryText: "#525252",
    accent: "#ff5500",
    codeBg: "#0a0a0a",
    codeTextColor: "#fafafa",
    quoteBorder: "#0a0a0a",
    calloutBg: "#ffe4d6",
    tableBorder: "#0a0a0a",
    divider: "#0a0a0a",
    watermark: "#a3a3a3",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 38,
    cardRadius: 0,
    cardBorder: "2px solid #0a0a0a",
    cardShadow: "6px 6px 0 #0a0a0a",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 20. Risograph ────────────────────────────────────────────
  {
    id: "risograph",
    name: "Risograph",
    nameEn: "Risograph",
    description: "孔版印刷，荧光油墨手感",
    tags: ["浅色", "印刷"],
    mode: "light",
    titleFont: "'Fraunces', 'Noto Serif SC', Georgia, serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 28,
    titleFontWeight: 600,
    titleLineHeight: 1.25,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0.005em",
    background: "#faf5ec",
    cardBg: "#fffaf0",
    textColor: "#2c2825",
    secondaryText: "#8a7d6e",
    accent: "#f06f6f",
    codeBg: "#f5ede0",
    quoteBorder: "#d4c5a8",
    calloutBg: "#fdf2e0",
    tableBorder: "#d4c5a8",
    divider: "#e5d8c4",
    watermark: "#b8a690",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 42,
    cardPaddingY: 40,
    cardRadius: 4,
    cardBorder: "1px solid #d4c5a8",
    cardShadow: "4px 4px 0 rgba(240,111,111,0.18)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },
];
