import type { CardTheme } from "../types";

export const TECH_THEMES: CardTheme[] = [
  // ── 1. Notion ────────────────────────────────────────────────
  {
    id: "notion",
    name: "Notion 白",
    nameEn: "Notion",
    description: "极简专业，文档感",
    tags: ["极简", "文档"],
    mode: "light",
    titleFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', monospace",
    titleFontSize: 28,
    titleFontWeight: 700,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.02em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0",
    background: "#ffffff",
    cardBg: "#ffffff",
    textColor: "#37352f",
    secondaryText: "#9ca3af",
    accent: "#2d6cdf",
    codeBg: "#f5f5f5",
    quoteBorder: "#e5e7eb",
    calloutBg: "#f9fafb",
    tableBorder: "#e5e7eb",
    divider: "#e5e7eb",
    watermark: "#e0e0e0",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 16,
    cardBorder: "1px solid #f0f0f0",
    cardShadow: "0 1px 3px rgba(0,0,0,0.02), 0 4px 12px rgba(0,0,0,0.03)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 2. Obsidian ──────────────────────────────────────────────
  {
    id: "obsidian",
    name: "Obsidian 夜",
    nameEn: "Obsidian",
    description: "深色模式，代码感",
    tags: ["深色", "技术"],
    mode: "dark",
    titleFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', monospace",
    titleFontSize: 26,
    titleFontWeight: 700,
    titleLineHeight: 1.35,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.8,
    bodyLetterSpacing: "0",
    background: "linear-gradient(160deg, #0d1117 0%, #161b22 50%, #0d1117 100%)",
    cardBg: "#161b22",
    textColor: "#e6edf3",
    secondaryText: "#8b949e",
    accent: "#58a6ff",
    codeBg: "#0d1117",
    quoteBorder: "#30363d",
    calloutBg: "#21262d",
    tableBorder: "#30363d",
    divider: "#30363d",
    watermark: "#6e7681",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 16,
    cardBorder: "1px solid #30363d",
    cardShadow: "0 8px 32px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.03)",
    showDecorations: true,
    decorationColor: "rgba(88,166,255,0.06)",
    watermarkVisible: true,
  },

  // ── 10. GitHub Light ─────────────────────────────────────────
  {
    id: "github-light",
    name: "GitHub 浅",
    nameEn: "GitHub Light",
    description: "GitHub 官方浅色，开发者友好",
    tags: ["浅色", "开发"],
    mode: "light",
    titleFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', 'Monaco', monospace",
    titleFontSize: 26,
    titleFontWeight: 600,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.005em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.7,
    bodyLetterSpacing: "0",
    background: "#ffffff",
    cardBg: "#ffffff",
    textColor: "#1f2328",
    secondaryText: "#59636e",
    accent: "#0969da",
    codeBg: "#f6f8fa",
    quoteBorder: "#d1d9e0",
    calloutBg: "#f6f8fa",
    tableBorder: "#d1d9e0",
    divider: "#d1d9e0",
    watermark: "#8b949e",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 12,
    cardBorder: "1px solid #d1d9e0",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 11. GitHub Dark ──────────────────────────────────────────
  {
    id: "github-dark",
    name: "GitHub 深",
    nameEn: "GitHub Dark",
    description: "GitHub 官方深色，平静专注",
    tags: ["深色", "开发"],
    mode: "dark",
    titleFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', -apple-system, 'Segoe UI', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', 'Monaco', monospace",
    titleFontSize: 26,
    titleFontWeight: 600,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.005em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.7,
    bodyLetterSpacing: "0",
    background: "#0d1117",
    cardBg: "#0d1117",
    textColor: "#e6edf3",
    secondaryText: "#8b949e",
    accent: "#2f81f7",
    codeBg: "#161b22",
    quoteBorder: "#30363d",
    calloutBg: "#161b22",
    tableBorder: "#30363d",
    divider: "#21262d",
    watermark: "#6e7681",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 36,
    cardRadius: 12,
    cardBorder: "1px solid #30363d",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 12. Vercel Geist ─────────────────────────────────────────
  {
    id: "vercel-dark",
    name: "Vercel 极黑",
    nameEn: "Vercel Geist",
    description: "纯黑极简，硬核现代",
    tags: ["深色", "极简"],
    mode: "dark",
    titleFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', monospace",
    titleFontSize: 34,
    titleFontWeight: 600,
    titleLineHeight: 1.15,
    titleLetterSpacing: "-0.03em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.7,
    bodyLetterSpacing: "-0.005em",
    background: "#0a0a0a",
    cardBg: "#0a0a0a",
    textColor: "#ededed",
    secondaryText: "#a1a1aa",
    accent: "#ffffff",
    codeBg: "#171717",
    quoteBorder: "#262626",
    calloutBg: "#141414",
    tableBorder: "#262626",
    divider: "#1f1f1f",
    watermark: "#8b8b93",
    containerPaddingX: 64,
    containerPaddingY: 64,
    cardPaddingX: 44,
    cardPaddingY: 44,
    cardRadius: 0,
    cardBorder: "1px solid #262626",
    cardShadow: "none",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 13. Tokyo Night ──────────────────────────────────────────
  {
    id: "tokyo-night",
    name: "东京之夜",
    nameEn: "Tokyo Night",
    description: "深蓝紫调，编辑器经典",
    tags: ["深色", "代码"],
    mode: "dark",
    titleFont: "'Inter', 'JetBrains Mono', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', 'SF Mono', monospace",
    titleFontSize: 28,
    titleFontWeight: 600,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.75,
    bodyLetterSpacing: "0",
    background: "linear-gradient(155deg, #1a1b26 0%, #1f2335 100%)",
    cardBg: "#24283b",
    textColor: "#c0caf5",
    secondaryText: "#9aa5ce",
    accent: "#7aa2f7",
    codeBg: "#1f2335",
    quoteBorder: "#414868",
    calloutBg: "#292e42",
    tableBorder: "#414868",
    divider: "#292e42",
    watermark: "#7a83b0",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 42,
    cardPaddingY: 38,
    cardRadius: 14,
    cardBorder: "1px solid #292e42",
    cardShadow: "0 12px 36px rgba(0,0,0,0.45), inset 0 0 0 1px rgba(255,255,255,0.02)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 14. Catppuccin Macchiato ─────────────────────────────────
  {
    id: "catppuccin",
    name: "Catppuccin",
    nameEn: "Macchiato",
    description: "柔和粉调暗色，开发者最爱",
    tags: ["深色", "柔和"],
    mode: "dark",
    titleFont: "'Inter', 'Noto Sans SC', sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 28,
    titleFontWeight: 600,
    titleLineHeight: 1.3,
    titleLetterSpacing: "-0.01em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.75,
    bodyLetterSpacing: "0",
    background: "#24273a",
    cardBg: "#1e2030",
    textColor: "#cad3f5",
    secondaryText: "#a5adcb",
    accent: "#c6a0f6",
    codeBg: "#181926",
    quoteBorder: "#494d64",
    calloutBg: "#363a4f",
    tableBorder: "#494d64",
    divider: "#363a4f",
    watermark: "#6e738d",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 40,
    cardPaddingY: 38,
    cardRadius: 14,
    cardBorder: "1px solid #363a4f",
    cardShadow: "0 10px 30px rgba(0,0,0,0.35)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },

  // ── 16. Linear ───────────────────────────────────────────────
  {
    id: "linear",
    name: "Linear",
    nameEn: "Linear",
    description: "几何冷感，工程师审美",
    tags: ["浅色", "几何"],
    mode: "light",
    titleFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    bodyFont: "'Inter', 'Noto Sans SC', -apple-system, sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    titleFontSize: 30,
    titleFontWeight: 600,
    titleLineHeight: 1.2,
    titleLetterSpacing: "-0.025em",
    titleAlign: "left",
    bodyFontSize: 15,
    bodyLineHeight: 1.7,
    bodyLetterSpacing: "-0.005em",
    background: "linear-gradient(180deg, #ffffff 0%, #fafbfc 100%)",
    cardBg: "#ffffff",
    textColor: "#1c1d22",
    secondaryText: "#6e7079",
    accent: "#5e6ad2",
    codeBg: "#f7f8fa",
    quoteBorder: "#ebebee",
    calloutBg: "#f7f8fa",
    tableBorder: "#ebebee",
    divider: "#ebebee",
    watermark: "#b8b8c0",
    containerPaddingX: 56,
    containerPaddingY: 56,
    cardPaddingX: 42,
    cardPaddingY: 40,
    cardRadius: 14,
    cardBorder: "1px solid #ebebee",
    cardShadow: "0 1px 2px rgba(0,0,0,0.04), 0 10px 30px rgba(0,0,0,0.04)",
    showDecorations: false,
    decorationColor: "transparent",
    watermarkVisible: true,
  },
];
