/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AUTO_CLOSE_INACTIVE_TABS_HOURS_DEFAULT: typeof import('./stores/settings/index').AUTO_CLOSE_INACTIVE_TABS_HOURS_DEFAULT
  const AUTO_CLOSE_INACTIVE_TABS_HOURS_MAX: typeof import('./stores/settings/index').AUTO_CLOSE_INACTIVE_TABS_HOURS_MAX
  const AUTO_CLOSE_INACTIVE_TABS_HOURS_MIN: typeof import('./stores/settings/index').AUTO_CLOSE_INACTIVE_TABS_HOURS_MIN
  const Activity: typeof import('react').Activity
  const AiGradientIcon: typeof import('./components/ui/ai-gradient-icon').AiGradientIcon
  const Badge: typeof import('./components/ui/badge').Badge
  const Button: typeof import('./components/ui/button').Button
  const CARD_THEMES: typeof import('./lib/imageExport/index').CARD_THEMES
  const Card: typeof import('./components/ui/card').Card
  const CardContent: typeof import('./components/ui/card').CardContent
  const CardDescription: typeof import('./components/ui/card').CardDescription
  const CardFooter: typeof import('./components/ui/card').CardFooter
  const CardHeader: typeof import('./components/ui/card').CardHeader
  const CardTitle: typeof import('./components/ui/card').CardTitle
  const ContextMenu: typeof import('./components/ui/context-menu').ContextMenu
  const ContextMenuCheckboxItem: typeof import('./components/ui/context-menu').ContextMenuCheckboxItem
  const ContextMenuContent: typeof import('./components/ui/context-menu').ContextMenuContent
  const ContextMenuGroup: typeof import('./components/ui/context-menu').ContextMenuGroup
  const ContextMenuItem: typeof import('./components/ui/context-menu').ContextMenuItem
  const ContextMenuLabel: typeof import('./components/ui/context-menu').ContextMenuLabel
  const ContextMenuPortal: typeof import('./components/ui/context-menu').ContextMenuPortal
  const ContextMenuRadioGroup: typeof import('./components/ui/context-menu').ContextMenuRadioGroup
  const ContextMenuRadioItem: typeof import('./components/ui/context-menu').ContextMenuRadioItem
  const ContextMenuSeparator: typeof import('./components/ui/context-menu').ContextMenuSeparator
  const ContextMenuShortcut: typeof import('./components/ui/context-menu').ContextMenuShortcut
  const ContextMenuSub: typeof import('./components/ui/context-menu').ContextMenuSub
  const ContextMenuSubContent: typeof import('./components/ui/context-menu').ContextMenuSubContent
  const ContextMenuSubTrigger: typeof import('./components/ui/context-menu').ContextMenuSubTrigger
  const ContextMenuTrigger: typeof import('./components/ui/context-menu').ContextMenuTrigger
  const DEFAULT_APP_SHORTCUTS: typeof import('./stores/settings/index').DEFAULT_APP_SHORTCUTS
  const DEFAULT_CLAUDE_BASE_URL: typeof import('./lib/ai-provider/index').DEFAULT_CLAUDE_BASE_URL
  const DEFAULT_CLOSE_TAB_SHORTCUT: typeof import('./stores/settings/index').DEFAULT_CLOSE_TAB_SHORTCUT
  const DEFAULT_FONT_NAMES: typeof import('./lib/fontLoader').DEFAULT_FONT_NAMES
  const DEFAULT_NOTEBOOK: typeof import('./stores/useNotebooks').DEFAULT_NOTEBOOK
  const DEFAULT_OPENAI_BASE_URL: typeof import('./lib/ai-provider/index').DEFAULT_OPENAI_BASE_URL
  const DEFAULT_SEARCH_HOTKEY: typeof import('./stores/settings/index').DEFAULT_SEARCH_HOTKEY
  const DEFAULT_SEARCH_PANEL_CLOSE_SHORTCUT: typeof import('./stores/settings/index').DEFAULT_SEARCH_PANEL_CLOSE_SHORTCUT
  const DEFAULT_SEARCH_PROVIDERS: typeof import('./stores/settings/index').DEFAULT_SEARCH_PROVIDERS
  const DEFAULT_WAKE_HOTKEY: typeof import('./stores/settings/index').DEFAULT_WAKE_HOTKEY
  const DEFAULT_WATERMARK_CONFIG: typeof import('./lib/imageExport/index').DEFAULT_WATERMARK_CONFIG
  const Dialog: typeof import('./components/ui/dialog').Dialog
  const DialogClose: typeof import('./components/ui/dialog').DialogClose
  const DialogContent: typeof import('./components/ui/dialog').DialogContent
  const DialogDescription: typeof import('./components/ui/dialog').DialogDescription
  const DialogFooter: typeof import('./components/ui/dialog').DialogFooter
  const DialogHeader: typeof import('./components/ui/dialog').DialogHeader
  const DialogOverlay: typeof import('./components/ui/dialog').DialogOverlay
  const DialogPortal: typeof import('./components/ui/dialog').DialogPortal
  const DialogShell: typeof import('./components/ui/dialog-shell').DialogShell
  const DialogTitle: typeof import('./components/ui/dialog').DialogTitle
  const DialogTrigger: typeof import('./components/ui/dialog').DialogTrigger
  const DropdownMenu: typeof import('./components/ui/dropdown-menu').DropdownMenu
  const DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu').DropdownMenuCheckboxItem
  const DropdownMenuContent: typeof import('./components/ui/dropdown-menu').DropdownMenuContent
  const DropdownMenuGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuGroup
  const DropdownMenuItem: typeof import('./components/ui/dropdown-menu').DropdownMenuItem
  const DropdownMenuLabel: typeof import('./components/ui/dropdown-menu').DropdownMenuLabel
  const DropdownMenuPortal: typeof import('./components/ui/dropdown-menu').DropdownMenuPortal
  const DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioGroup
  const DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioItem
  const DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu').DropdownMenuSeparator
  const DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu').DropdownMenuShortcut
  const DropdownMenuSub: typeof import('./components/ui/dropdown-menu').DropdownMenuSub
  const DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu').DropdownMenuSubContent
  const DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuSubTrigger
  const DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuTrigger
  const EDITOR_FONT_SIZE_DEFAULT: typeof import('./stores/settings/index').EDITOR_FONT_SIZE_DEFAULT
  const EDITOR_FONT_SIZE_MAX: typeof import('./stores/settings/index').EDITOR_FONT_SIZE_MAX
  const EDITOR_FONT_SIZE_MIN: typeof import('./stores/settings/index').EDITOR_FONT_SIZE_MIN
  const FeatureToastCard: typeof import('./components/ui/feature-toast-card').FeatureToastCard
  const FileTrigger: typeof import('./components/ui/file-trigger').FileTrigger
  const Fragment: typeof import('react').Fragment
  const IconButton: typeof import('./components/ui/icon-button').IconButton
  const ImageExportThemeSelector: typeof import('./components/ui/image-export-theme-selector').ImageExportThemeSelector
  const Input: typeof import('./components/ui/input').Input
  const Kbd: typeof import('./components/ui/kbd').Kbd
  const LEGACY_BLOCK_TYPES: typeof import('./components/editor/utils/blocknote-content/index').LEGACY_BLOCK_TYPES
  const LOCAL_FOLDER_EDITOR_CANDIDATES: typeof import('./lib/local-folder-open-apps').LOCAL_FOLDER_EDITOR_CANDIDATES
  const LOCAL_FOLDER_FILE_MANAGER_CANDIDATES: typeof import('./lib/local-folder-open-apps').LOCAL_FOLDER_FILE_MANAGER_CANDIDATES
  const LOCAL_FOLDER_TERMINAL_CANDIDATES: typeof import('./lib/local-folder-open-apps').LOCAL_FOLDER_TERMINAL_CANDIDATES
  const Label: typeof import('./components/ui/label').Label
  const LucideIcons: typeof import('lucide-react')
  const MAX_FILE_ATTACHMENT_SIZE: typeof import('./lib/fileStorage').MAX_FILE_ATTACHMENT_SIZE
  const ONBOARDING_CHILD_PAGE_CONTENT: typeof import('./lib/onboarding').ONBOARDING_CHILD_PAGE_CONTENT
  const ONBOARDING_PAGE_CONTENT: typeof import('./lib/onboarding').ONBOARDING_PAGE_CONTENT
  const ONBOARDING_SECOND_CHILD_CONTENT: typeof import('./lib/onboarding').ONBOARDING_SECOND_CHILD_CONTENT
  const Popover: typeof import('./components/ui/popover').Popover
  const PopoverAnchor: typeof import('./components/ui/popover').PopoverAnchor
  const PopoverContent: typeof import('./components/ui/popover').PopoverContent
  const PopoverTrigger: typeof import('./components/ui/popover').PopoverTrigger
  const Portal: typeof import('./components/ui/portal').Portal
  const Progress: typeof import('./components/ui/progress').Progress
  const QUICKNOTE_DEFAULT_HEIGHT: typeof import('./stores/useQuickNote').QUICKNOTE_DEFAULT_HEIGHT
  const QUICKNOTE_DEFAULT_WIDTH: typeof import('./stores/useQuickNote').QUICKNOTE_DEFAULT_WIDTH
  const QUICKNOTE_MIN_HEIGHT: typeof import('./stores/useQuickNote').QUICKNOTE_MIN_HEIGHT
  const QUICKNOTE_MIN_WIDTH: typeof import('./stores/useQuickNote').QUICKNOTE_MIN_WIDTH
  const ScrollArea: typeof import('./components/ui/scroll-area').ScrollArea
  const ScrollBar: typeof import('./components/ui/scroll-area').ScrollBar
  const SelectableCard: typeof import('./components/ui/selectable-card').SelectableCard
  const Separator: typeof import('./components/ui/separator').Separator
  const Sheet: typeof import('./components/ui/sheet').Sheet
  const SheetClose: typeof import('./components/ui/sheet').SheetClose
  const SheetContent: typeof import('./components/ui/sheet').SheetContent
  const SheetDescription: typeof import('./components/ui/sheet').SheetDescription
  const SheetFooter: typeof import('./components/ui/sheet').SheetFooter
  const SheetHeader: typeof import('./components/ui/sheet').SheetHeader
  const SheetOverlay: typeof import('./components/ui/sheet').SheetOverlay
  const SheetPortal: typeof import('./components/ui/sheet').SheetPortal
  const SheetTitle: typeof import('./components/ui/sheet').SheetTitle
  const SheetTrigger: typeof import('./components/ui/sheet').SheetTrigger
  const Slider: typeof import('./components/ui/slider').Slider
  const Suspense: typeof import('react').Suspense
  const Switch: typeof import('./components/ui/switch').Switch
  const TIPS: typeof import('./lib/tips').TIPS
  const TITLE_HEADING_LEVEL: typeof import('./components/editor/utils/blocknote-content/index').TITLE_HEADING_LEVEL
  const Table: typeof import('./components/ui/table').Table
  const TableBody: typeof import('./components/ui/table').TableBody
  const TableCaption: typeof import('./components/ui/table').TableCaption
  const TableCell: typeof import('./components/ui/table').TableCell
  const TableFooter: typeof import('./components/ui/table').TableFooter
  const TableHead: typeof import('./components/ui/table').TableHead
  const TableHeader: typeof import('./components/ui/table').TableHeader
  const TableRow: typeof import('./components/ui/table').TableRow
  const Tabs: typeof import('./components/ui/tabs').Tabs
  const TabsContent: typeof import('./components/ui/tabs').TabsContent
  const TabsList: typeof import('./components/ui/tabs').TabsList
  const TabsTrigger: typeof import('./components/ui/tabs').TabsTrigger
  const Textarea: typeof import('./components/ui/textarea').Textarea
  const Toaster: typeof import('./components/ui/sonner').Toaster
  const Toggle: typeof import('./components/ui/toggle').Toggle
  const Tooltip: typeof import('./components/ui/tooltip').Tooltip
  const TooltipContent: typeof import('./components/ui/tooltip').TooltipContent
  const TooltipProvider: typeof import('./components/ui/tooltip').TooltipProvider
  const TooltipTrigger: typeof import('./components/ui/tooltip').TooltipTrigger
  const UTOOLS_WINDOW_HEIGHT_DEFAULT: typeof import('./stores/settings/index').UTOOLS_WINDOW_HEIGHT_DEFAULT
  const UTOOLS_WINDOW_HEIGHT_MAX: typeof import('./stores/settings/index').UTOOLS_WINDOW_HEIGHT_MAX
  const UTOOLS_WINDOW_HEIGHT_MIN: typeof import('./stores/settings/index').UTOOLS_WINDOW_HEIGHT_MIN
  const UToolsAdapter: typeof import('./lib/utools').UToolsAdapter
  const UnderlineType: typeof import('./lib/docxExport/docxStyles').UnderlineType
  const VALID_BLOCK_TYPES: typeof import('./components/editor/utils/blocknote-content/index').VALID_BLOCK_TYPES
  const WELCOME_TAB_PAGE_ID: typeof import('./stores/useTabs').WELCOME_TAB_PAGE_ID
  const activateNotebook: typeof import('./lib/notebookNavigation').activateNotebook
  const applyBlockTypeTransformToEditor: typeof import('./lib/ai-write/index').applyBlockTypeTransformToEditor
  const applyFontVariables: typeof import('./lib/fontLoader').applyFontVariables
  const applyRolldownPolyfills: typeof import('./lib/rolldown-polyfill').applyRolldownPolyfills
  const applyTrailingNewlineStyle: typeof import('./lib/local-md-snapshot').applyTrailingNewlineStyle
  const badgeVariants: typeof import('./components/ui/badge').badgeVariants
  const blobToBase64: typeof import('./lib/imageProcessor').blobToBase64
  const blockToTable: typeof import('./lib/docxExport/docxBlocks').blockToTable
  const blocksToHTML: typeof import('./lib/export/index').blocksToHTML
  const blocksToMarkdown: typeof import('./lib/export/index').blocksToMarkdown
  const buildAiContextBundle: typeof import('./lib/ai-write/index').buildAiContextBundle
  const buildAiWorkspaceUserPrompt: typeof import('./lib/ai-write/index').buildAiWorkspaceUserPrompt
  const buildAiWritePlan: typeof import('./lib/ai-write/index').buildAiWritePlan
  const buildLocalPageId: typeof import('./lib/local-folder-scanner').buildLocalPageId
  const buildQuickNoteDraftPage: typeof import('./stores/useQuickNote').buildQuickNoteDraftPage
  const buttonVariants: typeof import('./components/ui/button').buttonVariants
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const clearAllLocalMdSnapshots: typeof import('./lib/local-md-snapshot').clearAllLocalMdSnapshots
  const clearLocalPageMetadataCache: typeof import('./stores/pages/index').clearLocalPageMetadataCache
  const clipboardHasPasteableImage: typeof import('./components/editor/utils/pasteClipboardImage').clipboardHasPasteableImage
  const clonePageContent: typeof import('./components/editor/utils/blocknote-content/index').clonePageContent
  const closeAllOverlays: typeof import('./lib/closeAllOverlays').closeAllOverlays
  const clsx: typeof import('clsx').clsx
  const cn: typeof import('./lib/utils').cn
  const commitAiWritePlan: typeof import('./lib/ai-write/index').commitAiWritePlan
  const compressIfNeeded: typeof import('./lib/imageProcessor').compressIfNeeded
  const compressImage: typeof import('./lib/imageProcessor').compressImage
  const confirmLocalDelete: typeof import('./lib/confirm-local-delete').confirmLocalDelete
  const containsMarkdownTable: typeof import('./lib/markdownTableParser').containsMarkdownTable
  const countWords: typeof import('./components/editor/utils/content-text-extractor').countWords
  const createAiChatOnlyTarget: typeof import('./lib/ai-write/index').createAiChatOnlyTarget
  const createBlockTypeTransformSelectionSnapshot: typeof import('./lib/ai-write/index').createBlockTypeTransformSelectionSnapshot
  const createContext: typeof import('react').createContext
  const createDebounce: typeof import('./components/editor/utils/debounce').createDebounce
  const createEditorSafeContent: typeof import('./components/editor/utils/blocknote-content/index').createEditorSafeContent
  const createEmptyBlockNoteContent: typeof import('./components/editor/utils/blocknote-content/index').createEmptyBlockNoteContent
  const createEmptyLocalPageContent: typeof import('./components/editor/utils/blocknote-content/index').createEmptyLocalPageContent
  const createPageBodyBlockTypeTransformSnapshot: typeof import('./lib/ai-write/index').createPageBodyBlockTypeTransformSnapshot
  const createRef: typeof import('react').createRef
  const createStickyTargetFromResolvedTarget: typeof import('./lib/ai-write/index').createStickyTargetFromResolvedTarget
  const decodeUnsupportedMarkdownForDisk: typeof import('./lib/markdown-raw-guard').decodeUnsupportedMarkdownForDisk
  const deleteLocalMdSnapshot: typeof import('./lib/local-md-snapshot').deleteLocalMdSnapshot
  const deletePageWithUndo: typeof import('./lib/page-delete-actions').deletePageWithUndo
  const deleteWebdavBackup: typeof import('./lib/webdavSync').deleteWebdavBackup
  const detectBlockScopeHeuristic: typeof import('./lib/ai-block-scope').detectBlockScopeHeuristic
  const downloadWebdavBackup: typeof import('./lib/webdavSync').downloadWebdavBackup
  const emptyBlock: typeof import('./components/editor/utils/blocknote-content/index').emptyBlock
  const encodeUnsupportedMarkdownForEditor: typeof import('./lib/markdown-raw-guard').encodeUnsupportedMarkdownForEditor
  const ensureFilenameAsTitle: typeof import('./lib/local-title-binding').ensureFilenameAsTitle
  const ensureFirstTitleHeading: typeof import('./components/editor/utils/blocknote-content/index').ensureFirstTitleHeading
  const exportNotebooks: typeof import('./lib/export/index').exportNotebooks
  const exportPageToImage: typeof import('./lib/imageExport/index').exportPageToImage
  const exportSelectionToImage: typeof import('./lib/imageExport/index').exportSelectionToImage
  const exportToHTML: typeof import('./lib/export/index').exportToHTML
  const exportToImage: typeof import('./lib/imageExport/index').exportToImage
  const exportToJSON: typeof import('./lib/export/index').exportToJSON
  const exportToMarkdown: typeof import('./lib/export/index').exportToMarkdown
  const exportToPDF: typeof import('./lib/export/index').exportToPDF
  const exportToWord: typeof import('./lib/docxExport/index').exportToWord
  const extractBlockNoteTitle: typeof import('./components/editor/utils/blocknote-content/index').extractBlockNoteTitle
  const extractBlocksInRange: typeof import('./lib/ai-block-scope').extractBlocksInRange
  const extractCellText: typeof import('./lib/docxExport/docxBlocks').extractCellText
  const extractFirstHeadingText: typeof import('./lib/local-title-binding').extractFirstHeadingText
  const extractFrontmatter: typeof import('./lib/markdown-raw-guard').extractFrontmatter
  const extractInlineItems: typeof import('./lib/docxExport/docxStyles').extractInlineItems
  const extractPlainText: typeof import('./components/editor/utils/blocknote-content/index').extractPlainText
  const extractStructureSummary: typeof import('./components/editor/utils/content-text-extractor').extractStructureSummary
  const extractTextFromContent: typeof import('./components/editor/utils/content-text-extractor').extractTextFromContent
  const extractTitleFromContent: typeof import('./components/editor/utils/content-text-extractor').extractTitleFromContent
  const fetchCustomAIModels: typeof import('./lib/ai-provider/index').fetchCustomAIModels
  const fileStorage: typeof import('./lib/fileStorage').fileStorage
  const findPseudoStructureMarkers: typeof import('./lib/ai-write/index').findPseudoStructureMarkers
  const flushEditorContent: typeof import('./stores/pages/index').flushEditorContent
  const flushUToolsStorageWrites: typeof import('./lib/storage').flushUToolsStorageWrites
  const formatAttachmentSize: typeof import('./lib/fileStorage').formatAttachmentSize
  const formatLocalFolderOpenAppName: typeof import('./lib/local-folder-open-apps').formatLocalFolderOpenAppName
  const formatShortcut: typeof import('./lib/utils').formatShortcut
  const forwardRef: typeof import('react').forwardRef
  const generateDocxBuffer: typeof import('./lib/docxExport/index').generateDocxBuffer
  const generateExportZip: typeof import('./lib/export/index').generateExportZip
  const getAIAvailability: typeof import('./lib/ai-provider/index').getAIAvailability
  const getAIProviderMode: typeof import('./lib/ai-provider/index').getAIProviderMode
  const getAttachmentBadgeLabel: typeof import('./lib/fileStorage').getAttachmentBadgeLabel
  const getAvailableAIModelOptions: typeof import('./lib/ai-provider/index').getAvailableAIModelOptions
  const getAvailableUToolsAiModels: typeof import('./lib/utools-ai').getAvailableUToolsAiModels
  const getBlockTypeTransformSignature: typeof import('./lib/ai-write/index').getBlockTypeTransformSignature
  const getBlockTypeTransformTargetLabel: typeof import('./lib/ai-write/index').getBlockTypeTransformTargetLabel
  const getCardTheme: typeof import('./lib/imageExport/index').getCardTheme
  const getContentSignature: typeof import('./components/editor/utils/blocknote-content/index').getContentSignature
  const getCustomAIApiKey: typeof import('./lib/ai-provider/index').getCustomAIApiKey
  const getCustomAIBaseURL: typeof import('./lib/ai-provider/index').getCustomAIBaseURL
  const getDbStorageItem: typeof import('./lib/storage').getDbStorageItem
  const getDefaultCustomAIBaseURL: typeof import('./lib/ai-provider/index').getDefaultCustomAIBaseURL
  const getEditorFontFamilies: typeof import('./lib/fontLoader').getEditorFontFamilies
  const getElementFromNode: typeof import('./components/editor/utils/selection').getElementFromNode
  const getFileUploadAvailability: typeof import('./lib/fileStorage').getFileUploadAvailability
  const getGlobalScrollActivitySnapshot: typeof import('./hooks/useGlobalScrollActivity').getGlobalScrollActivitySnapshot
  const getImageFromClipboard: typeof import('./lib/imageProcessor').getImageFromClipboard
  const getImageStorage: typeof import('./lib/docxExport/docxImages').getImageStorage
  const getLocalMdSnapshot: typeof import('./lib/local-md-snapshot').getLocalMdSnapshot
  const getPageTitle: typeof import('./components/editor/utils/page-title').getPageTitle
  const getPlatformKind: typeof import('./lib/utils').getPlatformKind
  const getPrimaryModifierKeyDisplay: typeof import('./lib/utils').getPrimaryModifierKeyDisplay
  const getPrimaryModifierKeyLabel: typeof import('./lib/utils').getPrimaryModifierKeyLabel
  const getQuicknoteSlashMenuFloatingOptions: typeof import('./components/editor/utils/quicknoteSlashMenuFloating').getQuicknoteSlashMenuFloatingOptions
  const getRandomTip: typeof import('./lib/tips').getRandomTip
  const getSelectedCellPlainText: typeof import('./components/editor/utils/selection').getSelectedCellPlainText
  const getSelectedPlainTextContext: typeof import('./components/editor/utils/selection').getSelectedPlainTextContext
  const getStoredAIModelOptions: typeof import('./lib/ai-provider/index').getStoredAIModelOptions
  const handleFileInsertion: typeof import('./components/editor/utils/handleClipboardFileInsertion').handleFileInsertion
  const hasStructuredBlocks: typeof import('./components/editor/utils/blocknote-content/index').hasStructuredBlocks
  const hasWholePageBlockTypeTransformScope: typeof import('./lib/ai-write/index').hasWholePageBlockTypeTransformScope
  const importFile: typeof import('./lib/export/index').importFile
  const importFromJSON: typeof import('./lib/export/index').importFromJSON
  const importFromMarkdown: typeof import('./lib/export/index').importFromMarkdown
  const importMarkdownFragment: typeof import('./lib/export/index').importMarkdownFragment
  const importNotebooksFromZip: typeof import('./lib/export/index').importNotebooksFromZip
  const inlineToTextRuns: typeof import('./lib/docxExport/docxStyles').inlineToTextRuns
  const inspectNotebookImportZip: typeof import('./lib/export/index').inspectNotebookImportZip
  const isBackupFileName: typeof import('./lib/webdavSync').isBackupFileName
  const isBlockNoteContent: typeof import('./components/editor/utils/blocknote-content/index').isBlockNoteContent
  const isBlockTypeTransformSelectionSnapshot: typeof import('./lib/ai-write/index').isBlockTypeTransformSelectionSnapshot
  const isBottomEditorBlankClick: typeof import('./components/editor/utils/selection').isBottomEditorBlankClick
  const isDiskContentMatchingSnapshot: typeof import('./lib/local-md-snapshot').isDiskContentMatchingSnapshot
  const isImageUploadFile: typeof import('./components/editor/utils/pasteClipboardImage').isImageUploadFile
  const isInsideToggle: typeof import('./components/editor/utils/toggleNesting').isInsideToggle
  const isInteractiveEditorTarget: typeof import('./components/editor/utils/selection').isInteractiveEditorTarget
  const isLinkworthyText: typeof import('./components/editor/utils/clipboard').isLinkworthyText
  const isLocalFolderDirectoryPage: typeof import('./lib/sidebarPageNavigation').isLocalFolderDirectoryPage
  const isLocalMdUnchanged: typeof import('./lib/local-md-snapshot').isLocalMdUnchanged
  const isMacPlatform: typeof import('./lib/utils').isMacPlatform
  const isPasteableClipboardImageFile: typeof import('./components/editor/utils/pasteClipboardImage').isPasteableClipboardImageFile
  const isPinyinQuery: typeof import('./lib/pinyin-search').isPinyinQuery
  const isToggleBlock: typeof import('./components/editor/utils/toggleNesting').isToggleBlock
  const isUToolsAiSupported: typeof import('./lib/utools-ai').isUToolsAiSupported
  const isValidImageUrl: typeof import('./lib/imageProcessor').isValidImageUrl
  const isValidUrl: typeof import('./components/editor/utils/clipboard').isValidUrl
  const jsonContentToMarkdown: typeof import('./lib/export/index').jsonContentToMarkdown
  const lazy: typeof import('react').lazy
  const listWebdavBackups: typeof import('./lib/webdavSync').listWebdavBackups
  const localFileTitleFromPath: typeof import('./lib/local-folder-scanner').localFileTitleFromPath
  const looksLikeBlockStructure: typeof import('./components/editor/utils/clipboard').looksLikeBlockStructure
  const looksLikeMarkdownFragment: typeof import('./components/editor/utils/clipboard').looksLikeMarkdownFragment
  const looksLikeMermaidDiagram: typeof import('./components/editor/utils/clipboard').looksLikeMermaidDiagram
  const mapUToolsAiModelsToOptions: typeof import('./lib/ai-provider/index').mapUToolsAiModelsToOptions
  const markSelfWrite: typeof import('./lib/local-md-snapshot').markSelfWrite
  const markUserInteraction: typeof import('./lib/editor-interaction-signal').markUserInteraction
  const matchShortcut: typeof import('./lib/shortcut-match').matchShortcut
  const memo: typeof import('react').memo
  const migrateCodeStyleTo2026: typeof import('./lib/code-style-migration').migrateCodeStyleTo2026
  const migrateLocalPageIdMapEntry: typeof import('./lib/local-page-idmap').migrateLocalPageIdMapEntry
  const migrateNotebookAiChatsState: typeof import('./stores/useNotebookAiChats').migrateNotebookAiChatsState
  const mimeToImageType: typeof import('./lib/docxExport/docxImages').mimeToImageType
  const normalizeBaseUrl: typeof import('./lib/webdavSync').normalizeBaseUrl
  const normalizeBlockContent: typeof import('./components/editor/utils/blocknote-content/index').normalizeBlockContent
  const normalizeBlocks: typeof import('./components/editor/utils/blocknote-content/index').normalizeBlocks
  const normalizeClipboardLineEndings: typeof import('./components/editor/utils/clipboard').normalizeClipboardLineEndings
  const normalizeExternalUrl: typeof import('./lib/openExternalUrl').normalizeExternalUrl
  const normalizeGeneratedStructureMarkdown: typeof import('./lib/ai-write/index').normalizeGeneratedStructureMarkdown
  const normalizeMarkdownPasteText: typeof import('./components/editor/utils/clipboard').normalizeMarkdownPasteText
  const normalizePageContent: typeof import('./components/editor/utils/blocknote-content/index').normalizePageContent
  const normalizeRemoteDir: typeof import('./lib/webdavSync').normalizeRemoteDir
  const normalizeWatermarkConfig: typeof import('./lib/imageExport/index').normalizeWatermarkConfig
  const onboardingChildPageContent: typeof import('./lib/onboardingContent').onboardingChildPageContent
  const onboardingPageContent: typeof import('./lib/onboardingContent').onboardingPageContent
  const onboardingSecondChildContent: typeof import('./lib/onboardingContent').onboardingSecondChildContent
  const openExternalUrl: typeof import('./lib/openExternalUrl').openExternalUrl
  const openPageFromSidebar: typeof import('./lib/sidebarPageNavigation').openPageFromSidebar
  const parseBase64Image: typeof import('./lib/docxExport/docxImages').parseBase64Image
  const parseLocalMarkdownContent: typeof import('./lib/local-folder-scanner').parseLocalMarkdownContent
  const parseMarkdownLink: typeof import('./components/editor/utils/clipboard').parseMarkdownLink
  const parseMarkdownTableToHtml: typeof import('./lib/markdownTableParser').parseMarkdownTableToHtml
  const parseMarkdownToHtml: typeof import('./lib/markdownTableParser').parseMarkdownToHtml
  const pasteClipboardFilesFromClipboard: typeof import('./components/editor/utils/pasteClipboardFilesFromClipboard').pasteClipboardFilesFromClipboard
  const permanentlyDeletePageWithCleanup: typeof import('./lib/page-delete-actions').permanentlyDeletePageWithCleanup
  const pinyinMatchIndices: typeof import('./lib/pinyin-search').pinyinMatchIndices
  const planBlockTypeTransform: typeof import('./lib/ai-write/index').planBlockTypeTransform
  const preloadFonts: typeof import('./lib/fontLoader').preloadFonts
  const processBlockChildren: typeof import('./lib/docxExport/docxBlocks').processBlockChildren
  const pruneLocalPageIdMap: typeof import('./lib/local-page-idmap').pruneLocalPageIdMap
  const readDbStorageJSON: typeof import('./lib/storage').readDbStorageJSON
  const readLocalPageIdMap: typeof import('./lib/local-page-idmap').readLocalPageIdMap
  const readPersistentDismissState: typeof import('./lib/dismiss-state').readPersistentDismissState
  const reconcileSlashSuggestionMenu: typeof import('./components/editor/utils/slashMenuPolicy').reconcileSlashSuggestionMenu
  const removeDbStorageItem: typeof import('./lib/storage').removeDbStorageItem
  const removeLocalPageIdMap: typeof import('./lib/local-page-idmap').removeLocalPageIdMap
  const renderExportHtml: typeof import('./lib/export/index').renderExportHtml
  const resolveAiTargetFromSelection: typeof import('./lib/ai-write/index').resolveAiTargetFromSelection
  const resolveAiTargetIntent: typeof import('./lib/ai-write/index').resolveAiTargetIntent
  const resolveAiTargetReference: typeof import('./lib/ai-write/index').resolveAiTargetReference
  const resolveAiTargetSelection: typeof import('./lib/ai-write/index').resolveAiTargetSelection
  const resolveBlockTypeTransformIntent: typeof import('./lib/ai-write/index').resolveBlockTypeTransformIntent
  const resolveExplicitBlockTypeTarget: typeof import('./lib/ai-write/index').resolveExplicitBlockTypeTarget
  const resolveGeneratedBlockStructureExpectation: typeof import('./lib/ai-write/index').resolveGeneratedBlockStructureExpectation
  const resolveImageMimeForUpload: typeof import('./components/editor/utils/pasteClipboardImage').resolveImageMimeForUpload
  const resolveImageToBuffer: typeof import('./lib/docxExport/docxImages').resolveImageToBuffer
  const resolveNotebookLandingPageId: typeof import('./lib/notebookNavigation').resolveNotebookLandingPageId
  const resolveOrCreateStableId: typeof import('./lib/local-page-idmap').resolveOrCreateStableId
  const resolveTheme: typeof import('./hooks/useResolvedTheme').resolveTheme
  const resolvedTargetToSelection: typeof import('./lib/ai-write/index').resolvedTargetToSelection
  const restorePageWithToast: typeof import('./lib/page-delete-actions').restorePageWithToast
  const runAIText: typeof import('./lib/ai-provider/index').runAIText
  const runAITextStream: typeof import('./lib/ai-provider/index').runAITextStream
  const runCodeStyleMigration2026: typeof import('./lib/code-style-migration').runCodeStyleMigration2026
  const sanitizeFileName: typeof import('./lib/fileStorage').sanitizeFileName
  const sanitizeFilenameSegment: typeof import('./lib/local-title-binding').sanitizeFilenameSegment
  const saveBlobAndReveal: typeof import('./lib/export/index').saveBlobAndReveal
  const saveBlobWithPrompt: typeof import('./lib/export/index').saveBlobWithPrompt
  const scanLocalFolderPages: typeof import('./lib/local-folder-scanner').scanLocalFolderPages
  const selectExpandedIds: typeof import('./stores/useSidebarView').selectExpandedIds
  const selectFavoritesCollapsed: typeof import('./stores/useSidebarView').selectFavoritesCollapsed
  const selectFocusedId: typeof import('./stores/useSidebarView').selectFocusedId
  const selectSelectedId: typeof import('./stores/useSidebarView').selectSelectedId
  const setDbStorageItem: typeof import('./lib/storage').setDbStorageItem
  const setLocalMdSnapshot: typeof import('./lib/local-md-snapshot').setLocalMdSnapshot
  const shortcutHasModifier: typeof import('./lib/shortcut-match').shortcutHasModifier
  const shouldIgnoreEntry: typeof import('./lib/local-folder-scanner').shouldIgnoreEntry
  const shouldIgnoreLocalRelativePath: typeof import('./lib/local-folder-scanner').shouldIgnoreLocalRelativePath
  const shouldOpenSlashSuggestionMenu: typeof import('./components/editor/utils/slashMenuPolicy').shouldOpenSlashSuggestionMenu
  const shouldPreferVisibleSelectionText: typeof import('./components/editor/utils/clipboard').shouldPreferVisibleSelectionText
  const shouldSuppressSidebarSelect: typeof import('./lib/sidebarPageNavigation').shouldSuppressSidebarSelect
  const shouldUploadViaImageStorage: typeof import('./components/editor/utils/pasteClipboardImage').shouldUploadViaImageStorage
  const simpleExtractText: typeof import('./components/editor/utils/blocknote-content/index').simpleExtractText
  const splitFilePath: typeof import('./lib/local-title-binding').splitFilePath
  const startTransition: typeof import('react').startTransition
  const stickyTargetToSelection: typeof import('./lib/ai-write/index').stickyTargetToSelection
  const stripMarkdownHardBreaks: typeof import('./components/editor/utils/clipboard').stripMarkdownHardBreaks
  const subscribeGlobalScrollActivity: typeof import('./hooks/useGlobalScrollActivity').subscribeGlobalScrollActivity
  const testWebdavConnection: typeof import('./lib/webdavSync').testWebdavConnection
  const titleHeadingBlock: typeof import('./components/editor/utils/blocknote-content/index').titleHeadingBlock
  const toRelativePath: typeof import('./lib/local-page-idmap').toRelativePath
  const toggleVariants: typeof import('./components/ui/toggle').toggleVariants
  const triggerAutoWebdavBackup: typeof import('./lib/webdavSync').triggerAutoWebdavBackup
  const uToolsStorage: typeof import('./lib/storage').uToolsStorage
  const updateSnapshotAfterWrite: typeof import('./lib/local-md-snapshot').updateSnapshotAfterWrite
  const uploadEditorFile: typeof import('./components/editor/utils/uploadEditorFile').uploadEditorFile
  const uploadWebdavBackup: typeof import('./lib/webdavSync').uploadWebdavBackup
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAiSessions: typeof import('./stores/useAiSessions').useAiSessions
  const useAiStatus: typeof import('./stores/useAiStatus').useAiStatus
  const useAppHotkeys: typeof import('./hooks/useAppHotkeys').useAppHotkeys
  const useCallback: typeof import('react').useCallback
  const useCompactViewport: typeof import('./hooks/useCompactViewport').useCompactViewport
  const useContext: typeof import('react').useContext
  const useContextMenu: typeof import('./components/editor/state/contextMenu').useContextMenu
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDeletePageWithUndo: typeof import('./hooks/useDeletePageWithUndo').useDeletePageWithUndo
  const useEditorFind: typeof import('./components/editor/hooks/useEditorFind').useEditorFind
  const useEditorPaste: typeof import('./components/editor/hooks/useEditorPaste').useEditorPaste
  const useEditorShortcuts: typeof import('./components/editor/hooks/useEditorShortcuts').useEditorShortcuts
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useFormatCode: typeof import('./components/editor/hooks/useFormatCode').useFormatCode
  const useFormattingToolbarAi: typeof import('./components/editor/state/formattingToolbarAi').useFormattingToolbarAi
  const useGlobalScrollActivity: typeof import('./components/editor/hooks/useGlobalScrollActivity').useGlobalScrollActivity
  const useHistoryRecorder: typeof import('./hooks/useHistoryRecorder').useHistoryRecorder
  const useHistoryView: typeof import('./stores/useHistoryView').useHistoryView
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useNativeContextMenuGuard: typeof import('./hooks/useNativeContextMenuGuard').useNativeContextMenuGuard
  const useNotebookAiChats: typeof import('./stores/useNotebookAiChats').useNotebookAiChats
  const useNotebooks: typeof import('./stores/useNotebooks').useNotebooks
  const useOptimistic: typeof import('react').useOptimistic
  const usePages: typeof import('./stores/pages/index').usePages
  const usePersistentDismissState: typeof import('./hooks/usePersistentDismissState').usePersistentDismissState
  const usePluginEvents: typeof import('./hooks/usePluginEvents').usePluginEvents
  const useQuickNote: typeof import('./stores/useQuickNote').useQuickNote
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedTheme: typeof import('./hooks/useResolvedTheme').useResolvedTheme
  const useSettings: typeof import('./stores/settings/index').useSettings
  const useSidebarView: typeof import('./stores/useSidebarView').useSidebarView
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTabs: typeof import('./stores/useTabs').useTabs
  const useTransition: typeof import('react').useTransition
  const validateGeneratedBlockStructure: typeof import('./lib/ai-write/index').validateGeneratedBlockStructure
  const waitForFonts: typeof import('./lib/fontLoader').waitForFonts
  const wasRecentlyInteracting: typeof import('./lib/editor-interaction-signal').wasRecentlyInteracting
  const wasRecentlySelfWritten: typeof import('./lib/local-md-snapshot').wasRecentlySelfWritten
  const writeDbStorageJSON: typeof import('./lib/storage').writeDbStorageJSON
  const writeLocalPageIdMap: typeof import('./lib/local-page-idmap').writeLocalPageIdMap
  const writePersistentDismissState: typeof import('./lib/dismiss-state').writePersistentDismissState
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ResolvedTheme } from './hooks/useResolvedTheme'
  import('./hooks/useResolvedTheme')
  // @ts-ignore
  export type { AiActivityPhase } from './stores/useAiStatus'
  import('./stores/useAiStatus')
  // @ts-ignore
  export type { NotebookAiConversation, NotebookAiNotebookChatState, NotebookAiChatsState } from './stores/useNotebookAiChats'
  import('./stores/useNotebookAiChats')
  // @ts-ignore
  export type { Notebook, LocalFolderLoadStatus, LocalFolderLoadState } from './stores/useNotebooks'
  import('./stores/useNotebooks')
  // @ts-ignore
  export type { SettingsState, SearchProvider, Theme, CodeStyle, UToolsSettings, AISettings, DesktopHotkeyStatusState, DesktopHotkeyStatus, DesktopSettings, PrivacySettings, FontConfig, CustomFonts, CustomAction, UIFontSize } from './stores/settings/index'
  import('./stores/settings/index')
  // @ts-ignore
  export type { TabItem } from './stores/useTabs'
  import('./stores/useTabs')
  // @ts-ignore
  export type { AiBlockScopeKind, AiBlockScopeRange, AiBlockScope } from './lib/ai-block-scope'
  import('./lib/ai-block-scope')
  // @ts-ignore
  export type { CustomAIProtocol, AIModelOption, AIProviderMode, AIReasoningLevel, AISettingsLike, AIMessage, AIStreamPhase, AIStreamUpdate, AIRequestOverrides, RunAITextOptions, RunAITextStreamOptions } from './lib/ai-provider/index'
  import('./lib/ai-provider/index')
  // @ts-ignore
  export type { AiWriteAction, AiBlockRange, AiTargetMode, AiTargetSource, AiTargetSelection, AiTargetRef, AiStickyTarget, AiResolvedTarget, AiWritePlan, AiContextBundle, BlockTypeTransformIntent, BlockTypeTransformBlock, BlockTypeTransformPanelOpenDetail, BlockTypeTransformPlan, BlockTypeTransformResult, BlockTypeTransformSelectionSnapshot, BlockTypeTransformTarget, GeneratedBlockStructureExpectation, GeneratedBlockStructureValidationInput, GeneratedBlockStructureValidationResult, PseudoStructureMarkerIssue } from './lib/ai-write/index'
  import('./lib/ai-write/index')
  // @ts-ignore
  export type { InlineItem } from './lib/docxExport/docxStyles'
  import('./lib/docxExport/docxStyles')
  // @ts-ignore
  export type { ImageBufferResult } from './lib/docxExport/docxImages'
  import('./lib/docxExport/docxImages')
  // @ts-ignore
  export type { CardTheme, CardThemeId, WatermarkConfig } from './lib/imageExport/index'
  import('./lib/imageExport/index')
  // @ts-ignore
  export type { LocalFolderOpenAppKind, LocalFolderOpenAppCandidate } from './lib/local-folder-open-apps'
  import('./lib/local-folder-open-apps')
  // @ts-ignore
  export type { ParsedLocalMarkdown } from './lib/local-folder-scanner'
  import('./lib/local-folder-scanner')
  // @ts-ignore
  export type { LocalPageIdMap } from './lib/local-page-idmap'
  import('./lib/local-page-idmap')
  // @ts-ignore
  export type { PlatformKind } from './lib/utils'
  import('./lib/utils')
  // @ts-ignore
  export type { UToolsAiModel } from './lib/utools-ai'
  import('./lib/utools-ai')
  // @ts-ignore
  export type { UToolsAdapter, SublistItem, UserInfo } from './lib/utools'
  import('./lib/utools')
  // @ts-ignore
  export type { WebdavBackupFile } from './lib/webdavSync'
  import('./lib/webdavSync')
  // @ts-ignore
  export type { BadgeProps } from './components/ui/badge'
  import('./components/ui/badge')
  // @ts-ignore
  export type { ButtonProps } from './components/ui/button'
  import('./components/ui/button')
  // @ts-ignore
  export type { IconButtonProps } from './components/ui/icon-button'
  import('./components/ui/icon-button')
  // @ts-ignore
  export type { ProgressProps } from './components/ui/progress'
  import('./components/ui/progress')
  // @ts-ignore
  export type { SelectableCardProps } from './components/ui/selectable-card'
  import('./components/ui/selectable-card')
  // @ts-ignore
  export type { BlockNoteContent, LegacyPageContent, PageContent } from './components/editor/utils/blocknote-content/index'
  import('./components/editor/utils/blocknote-content/index')
  // @ts-ignore
  export type { SlashMenuPagePolicy } from './components/editor/utils/slashMenuPolicy'
  import('./components/editor/utils/slashMenuPolicy')
  // @ts-ignore
  export type { EditorFileUploadDeps } from './components/editor/utils/uploadEditorFile'
  import('./components/editor/utils/uploadEditorFile')
  // @ts-ignore
  export type { EditorFindState } from './components/editor/hooks/useEditorFind'
  import('./components/editor/hooks/useEditorFind')
}
